In [15]:
import pandas as pd
import numpy as np

In [9]:
data = pd.read_csv('5_formatted.csv').drop('Unnamed: 0', axis=1)

In [20]:
ex0 = data.ix[0]

In [23]:
ex0d = ex0.to_dict()

In [25]:
# each set of 5 becomes a column in our matrix
sorted(ex0d.items())

[('--1', 0),
 ('--2', 1),
 ('-0', 0),
 ('-1', 0),
 ('-2', 0),
 ('A-1', 0),
 ('A-2', 0),
 ('A0', 0),
 ('A1', 0),
 ('A2', 0),
 ('C-1', 0),
 ('C-2', 0),
 ('C0', 0),
 ('C1', 0),
 ('C2', 0),
 ('D-1', 0),
 ('D-2', 0),
 ('D0', 0),
 ('D1', 0),
 ('D2', 0),
 ('E-1', 0),
 ('E-2', 0),
 ('E0', 0),
 ('E1', 0),
 ('E2', 0),
 ('F-1', 0),
 ('F-2', 0),
 ('F0', 0),
 ('F1', 0),
 ('F2', 0),
 ('G-1', 0),
 ('G-2', 0),
 ('G0', 0),
 ('G1', 0),
 ('G2', 0),
 ('H-1', 0),
 ('H-2', 0),
 ('H0', 0),
 ('H1', 0),
 ('H2', 0),
 ('I-1', 0),
 ('I-2', 0),
 ('I0', 0),
 ('I1', 0),
 ('I2', 0),
 ('K-1', 0),
 ('K-2', 0),
 ('K0', 0),
 ('K1', 0),
 ('K2', 0),
 ('L-1', 0),
 ('L-2', 0),
 ('L0', 1),
 ('L1', 0),
 ('L2', 0),
 ('M-1', 0),
 ('M-2', 0),
 ('M0', 0),
 ('M1', 0),
 ('M2', 0),
 ('N-1', 0),
 ('N-2', 0),
 ('N0', 0),
 ('N1', 0),
 ('N2', 0),
 ('P-1', 0),
 ('P-2', 0),
 ('P0', 0),
 ('P1', 0),
 ('P2', 1),
 ('Q-1', 0),
 ('Q-2', 0),
 ('Q0', 0),
 ('Q1', 0),
 ('Q2', 0),
 ('R-1', 0),
 ('R-2', 0),
 ('R0', 0),
 ('R1', 0),
 ('R2', 0),
 ('S-1',

In [49]:
# get the sorting indices
indices = np.argsort(ex0d.keys())

# items_sorted = np.array(ex0d.items())[indices]
# print items_sorted.reshape(-1, 10)

# then get the values from the dict
vals_sorted = np.asarray(ex0d.values())[indices]

# then reshape as column, per 5
mat = vals_sorted.reshape(-1, 5).T

print mat

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]]


In [11]:
cols = list(data.columns)

In [12]:
cols

['A-2',
 'C-2',
 'D-2',
 'E-2',
 'F-2',
 'G-2',
 'H-2',
 'I-2',
 'K-2',
 'L-2',
 'M-2',
 'N-2',
 'P-2',
 'Q-2',
 'R-2',
 'S-2',
 'T-2',
 'V-2',
 'W-2',
 'Y-2',
 '--2',
 'A-1',
 'C-1',
 'D-1',
 'E-1',
 'F-1',
 'G-1',
 'H-1',
 'I-1',
 'K-1',
 'L-1',
 'M-1',
 'N-1',
 'P-1',
 'Q-1',
 'R-1',
 'S-1',
 'T-1',
 'V-1',
 'W-1',
 'Y-1',
 '--1',
 'A0',
 'C0',
 'D0',
 'E0',
 'F0',
 'G0',
 'H0',
 'I0',
 'K0',
 'L0',
 'M0',
 'N0',
 'P0',
 'Q0',
 'R0',
 'S0',
 'T0',
 'V0',
 'W0',
 'Y0',
 '-0',
 'A1',
 'C1',
 'D1',
 'E1',
 'F1',
 'G1',
 'H1',
 'I1',
 'K1',
 'L1',
 'M1',
 'N1',
 'P1',
 'Q1',
 'R1',
 'S1',
 'T1',
 'V1',
 'W1',
 'Y1',
 '-1',
 'A2',
 'C2',
 'D2',
 'E2',
 'F2',
 'G2',
 'H2',
 'I2',
 'K2',
 'L2',
 'M2',
 'N2',
 'P2',
 'Q2',
 'R2',
 'S2',
 'T2',
 'V2',
 'W2',
 'Y2',
 '-2']

In [13]:
s = sorted(cols)

In [22]:
for i in xrange(0, len(s), 5):
    print s[i: i+5]

['--1', '--2', '-0', '-1', '-2']
['A-1', 'A-2', 'A0', 'A1', 'A2']
['C-1', 'C-2', 'C0', 'C1', 'C2']
['D-1', 'D-2', 'D0', 'D1', 'D2']
['E-1', 'E-2', 'E0', 'E1', 'E2']
['F-1', 'F-2', 'F0', 'F1', 'F2']
['G-1', 'G-2', 'G0', 'G1', 'G2']
['H-1', 'H-2', 'H0', 'H1', 'H2']
['I-1', 'I-2', 'I0', 'I1', 'I2']
['K-1', 'K-2', 'K0', 'K1', 'K2']
['L-1', 'L-2', 'L0', 'L1', 'L2']
['M-1', 'M-2', 'M0', 'M1', 'M2']
['N-1', 'N-2', 'N0', 'N1', 'N2']
['P-1', 'P-2', 'P0', 'P1', 'P2']
['Q-1', 'Q-2', 'Q0', 'Q1', 'Q2']
['R-1', 'R-2', 'R0', 'R1', 'R2']
['S-1', 'S-2', 'S0', 'S1', 'S2']
['T-1', 'T-2', 'T0', 'T1', 'T2']
['V-1', 'V-2', 'V0', 'V1', 'V2']
['W-1', 'W-2', 'W0', 'W1', 'W2']
['Y-1', 'Y-2', 'Y0', 'Y1', 'Y2']


In [16]:
letters = set()
indices = set()

for l in s:
    letters.add(l[0])
    indices.add(l[1:])

In [17]:
letters

{'-',
 'A',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'K',
 'L',
 'M',
 'N',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'V',
 'W',
 'Y'}

In [18]:
indices

{'-1', '-2', '0', '1', '2'}