In [3]:
import pandas as pd
import numpy as np
import pickle
import os

### Experimenting with simple example

In [4]:
data = pd.read_csv('../fixed_five.csv')
data.head()

A-2  C-2  D-2  E-2  F-2  G-2  H-2  I-2  K-2  L-2 ...    N2   P2   Q2   R2  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  1.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0 ...   0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   

    S2   T2   V2   W2   Y2   -2  
0  1.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 105 columns]

### Running with a single row example

In [5]:
ex0 = data.ix[0]
ex0d = ex0.to_dict()
# each set of 5 becomes a column in our matrix
sorted(ex0d.items())[:6]

[('--1', 1.0),
 ('--2', 1.0),
 ('-0', 0.0),
 ('-1', 0.0),
 ('-2', 0.0),
 ('A-1', 0.0)]

In [4]:
# get the sorting indices
indices = np.argsort(ex0d.keys())

items_sorted = np.array(ex0d.items())[indices]
print items_sorted.reshape(-1, 10)

# then get the values from the dict
vals_sorted = np.asarray(ex0d.values())[indices]

# then reshape as column, per 5
mat = vals_sorted.reshape(-1, 5).T

# formatted by AA Tag (cols) by position (rows)
# print mat

[['--1' '0' '--2' '1' '-0' '0' '-1' '0' '-2' '0']
 ['A-1' '0' 'A-2' '0' 'A0' '0' 'A1' '0' 'A2' '0']
 ['C-1' '0' 'C-2' '0' 'C0' '0' 'C1' '0' 'C2' '0']
 ['D-1' '0' 'D-2' '0' 'D0' '0' 'D1' '0' 'D2' '0']
 ['E-1' '0' 'E-2' '0' 'E0' '0' 'E1' '0' 'E2' '0']
 ['F-1' '0' 'F-2' '0' 'F0' '0' 'F1' '0' 'F2' '0']
 ['G-1' '0' 'G-2' '0' 'G0' '0' 'G1' '0' 'G2' '0']
 ['H-1' '0' 'H-2' '0' 'H0' '0' 'H1' '0' 'H2' '0']
 ['I-1' '0' 'I-2' '0' 'I0' '0' 'I1' '0' 'I2' '0']
 ['K-1' '0' 'K-2' '0' 'K0' '0' 'K1' '0' 'K2' '0']
 ['L-1' '0' 'L-2' '0' 'L0' '1' 'L1' '0' 'L2' '0']
 ['M-1' '0' 'M-2' '0' 'M0' '0' 'M1' '0' 'M2' '0']
 ['N-1' '0' 'N-2' '0' 'N0' '0' 'N1' '0' 'N2' '0']
 ['P-1' '0' 'P-2' '0' 'P0' '0' 'P1' '0' 'P2' '1']
 ['Q-1' '0' 'Q-2' '0' 'Q0' '0' 'Q1' '0' 'Q2' '0']
 ['R-1' '0' 'R-2' '0' 'R0' '0' 'R1' '0' 'R2' '0']
 ['S-1' '0' 'S-2' '0' 'S0' '0' 'S1' '1' 'S2' '0']
 ['T-1' '0' 'T-2' '0' 'T0' '0' 'T1' '0' 'T2' '0']
 ['V-1' '1' 'V-2' '0' 'V0' '0' 'V1' '0' 'V2' '0']
 ['W-1' '0' 'W-2' '0' 'W0' '0' 'W1' '0' 'W2' '0']


In [5]:
cols = list(data.columns)

In [6]:
s = sorted(cols)

In [7]:
amino_acids = set([s[0] for s in cols])
positions = set([s[1:] for s in cols])

positions = sorted(list(positions))
amino_acids = sorted(list(amino_acids))

In [8]:
for i in xrange(0, len(s), 5):
    print s[i: i+5]

-2


In [10]:
with pd.option_context('display.max_rows', 5, 'display.max_columns', 21):
    print ex_mat

    -  A  C  D  E  F  G  H  I  K  L  M  N  P  Q  R  S  T  V  W  Y
-1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0
-2  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
0   0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0
1   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0
2   0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0


## Now we need to do this conversion for the entire dataset

In [36]:
d = data.iterrows().next()[1].to_dict()

ind = np.argsort(d.keys())

v_sort = np.asarray(d.values())[indices]

print v_sort.reshape(-1, 5).T

data.shape

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]]


(134814, 105)

In [38]:
data_tensor = []

for i, ser in data.iterrows():
    d = ser.to_dict()
    indices = np.argsort(d.keys())
    # then get the values from the dict
    vals_sorted = np.asarray(d.values())[indices]

    # then reshape as column, per 5
    mat = vals_sorted.reshape(-1, 5).T
    
    data_tensor.append(mat)

In [39]:
data_tensor = np.asarray(data_tensor)

In [40]:
data_tensor[:2]

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]])

In [41]:
data_tensor.shape

(134814, 5, 21)

In [43]:
# saving the reformatted tensor as a pickle file
with open('5_tensor.p', 'wb') as f:
    pickle.dump(data_tensor, f)

In [44]:
# loading the saved tensor
with open('5_tensor.p', 'rb') as f:
    loaded_data = pickle.load(f)

In [46]:
loaded_data[:2]

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]])

## Working, now let's do it over the all of the possible skip-gram formats

In [47]:
# example filenames
s1 = 'data/cleaned_ord_11.csv'
s2 = 'data/cleaned_ord_13.csv'

# small helper function to handle extracting position spacing from filenames
def get_spacing(s):
    
    # start by reversing the string
    rev_s = s[::-1]
    
    # then find the first occurance of _ and .
    und = rev_s.find('_')
    per = rev_s.find('.')
    
    # spacing will then be a str which is
    # the number between the _ and . 
    space = rev_s[per+1:und]
    
    # finally, return the str
    # flipped back the right way
    return space[::-1]

# making sure it's working correctly
print get_spacing(s1)
print get_spacing(s2)

In [48]:
# run through the whole data directory
for dir_name, _, filenames in os.walk('data/'):
    for f in filenames:
        
        print 'starting with {0}'.format(f)
        
        # get the spacing number of the skip grams
        spacing = get_spacing(f)
        n_spacing = int(spacing)
        
        print 'spacing: {0}'.format(str(spacing))

        # load in the data to pandas
        data = pd.read_csv(dir_name+f).drop(['Unnamed: 0', 'pos', 'H', 'E', 'T', 'S', 'B', ' '], axis=1)
        
        # where we will store the data_tensor
        data_tensor = []

        for i, ser in data.iterrows():
            d = ser.to_dict()
            # get the sorting indices
            indices = np.argsort(d.keys())
            # then get the values from the dict
            vals_sorted = np.asarray(d.values())[indices]

            # then reshape as column, per spacing
            mat = vals_sorted.reshape(-1, n_spacing).T
            
            # construct the matrix
            data_tensor.append(mat)
        
        data_tensor = np.asarray(data_tensor)
        
        # finally, write the data for use later
        
        save_file = 'conv_data/' + spacing + '_tensor.p'
        
        with open(save_file, 'wb') as f:
            pickle.dump(data_tensor, f)
            
        print "finished with {0}".format(save_file)

starting with cleaned_ord_11.csv
spacing: 11
finished with conv_data/11_tensor.p
starting with cleaned_ord_13.csv
spacing: 13
finished with conv_data/13_tensor.p
starting with cleaned_ord_15.csv
spacing: 15
finished with conv_data/15_tensor.p
starting with cleaned_ord_17.csv
spacing: 17
finished with conv_data/17_tensor.p
starting with cleaned_ord_19.csv
spacing: 19
finished with conv_data/19_tensor.p
starting with cleaned_ord_5.csv
spacing: 5
finished with conv_data/5_tensor.p
starting with cleaned_ord_7.csv
spacing: 7
finished with conv_data/7_tensor.p
starting with cleaned_ord_9.csv
spacing: 9
finished with conv_data/9_tensor.p


## And we're done. Could parallelize the computation, but it's all good. 